name = "new_MIPTAutocorr"
uuid = "724b712f-9c1d-4787-a683-a3dfa2863efe"
version = "1.0.0-DEV"
authors = ["Gal Shkolnik <gal.shkolnik@mail.huji.ac.il> and contributors"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"

[compat]
Plots = "1.41.2"
QuantumClifford = "0.10.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
